[variables]
NPM_CONFIG_UPDATE_NOTIFIER = 'false'
NPM_CONFIG_FUND = 'false'

[phases.caddy]
dependsOn = ['setup']
nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301'
nixPkgs = ['caddy']

[phases.fmt]
dependsOn = ['caddy']
cmds = ['caddy fmt --overwrite Caddyfile']

[start]
cmd = 'exec caddy run --config Caddyfile --adapter caddyfile 2>&1'
